collections_dir: collections

collections:
  posts:
    output: true
    permalink: /blog/:title
  redirects:
    output: true
    permalink: /:path
  learn:
    output: true
    permalink: /:collection/:path

defaults:
  - scope: 
      type: redirects
    values:
      layout: redirect
  - scope:
      path: resume/index.html
    values:
      layout: resume
      header: transparent
      title: Braden Hitchcock | Resume

plugins:
  - jemoji
